### ISSUE TITLE
Let's share vim config

### ISSUE THREAD

**Issue by NSLog0** [avatarr/my-vimrc#1]
share vim config and earn Hacktoberfest T-Shirt

**Comment by Ishaan28malik** [comment]
hey i want to do this please help me and breif about it
...

**Comment by NSLog0** [comment]
@Ishaan28malik  Hi, Just share vim configuration or plugin that you think is worth to use for who use vim for software development. 

And if you want to specific more, Can you creata a setup dotfile for a new laptop ?

See #6
